language: cpp
sudo: true
dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - gcc-6

os:
  - linux
  - osx

env:
  - BUCKAROO_VERSION=buckaroo-redux-alpha-16

cache:
  directories:
    - $HOME/.buckaroo/cache
    - $TRAVIS_BUILD_DIR/bin

osx_image: xcode9.3

before_install:
  - ./travis/before-install-$TRAVIS_OS_NAME.sh

script:
  - ./bin/buckaroo install
  - ./bin/buck build -c ui.superconsole=DISABLED //:pixman-1
  - ./bin/buck build -c ui.superconsole=DISABLED //:solid-test
  - ./bin/buck run -c ui.superconsole=DISABLED //:oob-test
  - ./bin/buck run -c ui.superconsole=DISABLED //:blitters-test
