targets = [ "//:pixman-1" ]


[[dependency]]
package = "github.com/buckaroo-pm/host-m"
version = "branch=master"

[[dependency]]
package = "github.com/buckaroo-pm/host-pthread"
version = "branch=master"

[[dependency]]
package = "github.com/buckaroo-pm/luadist-libpng"
version = "branch=master"

[[dependency]]
package = "github.com/buckaroo-pm/madler-zlib"
version = "branch=master"
